### ISSUE TITLE
EPIC: Tennis Court Booking - Book

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/bushy-park-tennis-club-ld#16]
As a **user** I can **book a tennis court via the booking system** so that **I can easily reserve a time slot in which to play tennis at the club**

# Acceptance Criteria
- User can make a reservation object in the database using only front-end functionality
- Reservations are stored correctly in the database, with all fields correctly filled out
- User sees simplified reservation form, with user-friendly input fields & excluding fields to be populated with default values

# Tasks
- [x] Create Reservation model
- [x] Create user booking form page & form
- [x] Link user form to the database & insure that reservation objects are being created correctly
