### ISSUE TITLE
EPIC: User Profile

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/bushy-park-tennis-club-ld#25]
As a **user** I can **create a personalized user profile** so that **I can see my user details and other personalized information**

# Acceptance Criteria
- User profile is created automatically upon registration
- User can view their profile and see their information

# Tasks
- [x] Create Profile model in the database
- [x] Use signals to create the user profile automatically when user registers
- [x] Create a profile page to display user information
