### ISSUE TITLE
EPIC: User Registration

### ISSUE THREAD

**Issue by LewisMDillon** [LewisMDillon/bushy-park-tennis-club-ld#3]
As a **user** I can **create a secure account** so that **I can have a personal presence on the site, as well as access any account-based functionalities**

# Acceptance Criteria
- New users can see a link to register for an account
- New users can use a front-end registration form to create an account
- Registration form correctly creates user object in the relevant database model

# Tasks
- [x] Create register link in Navbar
- [x] Create user registration form
- [x] Link form to database & ensure objects are being created successfully
